import type {
  ConvertTaskParams,
  ConvertTaskResult,
  DocxParseResult,
  DocxParseTaskParams,
  HtmlGetByUrlResult,
  HtmlGetByUrlTaskParams,
  KeynoteParseResult,
  KeynoteParseTaskParams,
  PdfParseResult,
  PdfParseTaskParams,
  PptxParseResult,
  PptxParseTaskParams,
} from './parse/types.js';

export const DEFAULT_ROOT = 'https://app.deckflow.com/v1';
export const DEFAULT_TIMEOUT = 300;
export const DEFAULT_POLL_INTERVAL = 2000;
export const DEFAULT_CHUNK_SIZE = 10 * 1024 * 1024;
/** When creating a task with files under this total size, attach them inline as `files` instead of async upload + `fileIds`. */
export const INLINE_TASK_FILES_MAX_BYTES = 10 * 1024 * 1024;

export const DECK_TASK_TYPES = [
  'file.compress',
  'image.ocr',
  'pptx.split',
  'pptx.join',
  'pptx.getFontInfo',
  'pptx.getTextShapes',
  'pptx.embedFonts',
  'convertor.ppt2image',
  'convertor.ppt2pptx',
  'convertor.ppt2pdf',
  'convertor.doc2pdf',
  'convertor.ppt2video',
  'convertor.pdf2image',
  'convertor.keynote2image',
  'convertor.keynote2html',
  'convertor.keynote2pdf',
  'convertor.html2png',
  'convertor.markdown2png',
  'convertor.html2pptx',
  'html.buildPlayer',
  'video.compress',
  'image.convertWebp',
  'image.resize',
  'pdf.pdfParse',
  'pptx.parse',
  'docx.parseTextAndImage',
  'keynote.parseTextAndImage',
  'html.getByURL',
  'parse.convert',
  'generation',
  'translation',
  'revamp',
] as const;

export type DeckTaskType = (typeof DECK_TASK_TYPES)[number];
export type DeckTaskStatus = 'pending' | 'running' | 'completed' | 'failed';

export type MetadataValue =
  | string
  | number
  | boolean
  | null
  | MetadataValue[]
  | { [key: string]: MetadataValue };

export interface ConvertFileBounds {
  /** Width in pixels or document units. */
  w?: number;
  /** Height in pixels or document units. */
  h?: number;
  /** Total page/slide count when available. */
  total?: number;
}

export type FileResult = [
  /** Storage key, relative path, or URL after the backend expands task results. */
  path: string,
  /** File size in bytes. */
  bytes: number,
  /** MD5 hash. */
  hash: string,
];

export type ConvertFileResult = [
  /** Storage key, relative path, or URL after the backend expands task results. */
  path: string,
  /** File size in bytes. */
  bytes: number,
  /** MD5 hash. */
  hash: string,
  /** Optional conversion bounds/page metadata. */
  bounds?: ConvertFileBounds | null,
];

export interface DeckTask<T extends DeckTaskType = DeckTaskType> {
  /** Task id generated by the backend. */
  id: string;
  /** Space/workspace id owning this task. */
  spaceId: string;
  /** Task type. */
  type: T;
  /** Current task status. */
  status: DeckTaskStatus;
  /** Ordered input file ids. */
  fileIds?: string[];
  /** Task display name. */
  name?: string;
  /** Task parameters. */
  params?: DeckTaskTypeParams[T];
  /** Optional preview payload. */
  preview?: DeckTaskTypePreview[T];
  /** Task result payload. Prefer `tasks.down(taskId)` — detail responses no longer include results. */
  result?: DeckTaskTypeResult[T] | null;
  /** Error message for failed tasks. */
  error?: string | null;
  /** ISO create timestamp. */
  createdAt?: string;
  /** ISO update timestamp. */
  updatedAt?: string;
}

export interface TaskListResponse<T extends DeckTaskType = DeckTaskType> {
  /** Tasks in the requested page. */
  tasks: DeckTask<T>[];
  /** Total matching task count when the backend returns it. */
  total?: number;
}

export interface AuthUuidStorage {
  get(): string | null | undefined | Promise<string | null | undefined>;
  set(value: string): void | Promise<void>;
}

export interface CreateDeckOptions {
  /** API root address. Defaults to https://app.deckflow.com/v1. */
  root?: string;
  /** User auth token sent as X-Auth-Token. */
  token?: string;
  /** API key sent as Authorization: Bearer {apiKey}. */
  apiKey?: string;
  /** Default space id used by task and upload calls. When omitted, resolved from GET /user. */
  spaceId?: string;
  /** Explicit client UUID (UUID v4) sent as X-Auth-UUID. Skips automatic persistence. */
  authUuid?: string;
  /** Custom UUID storage for SSR, tests, or embedded integrations. */
  authUuidStorage?: AuthUuidStorage;
  /**
   * Called once after a 401 when a user token is present. Returned token is saved and the request is
   * retried. If omitted or refresh fails, the request fails unless allowGuestFallback is true.
   */
  onUnauthorized?: () => Promise<{ token: string; spaceId?: string } | string>;
  /** Permit a failed login to fall back to guest. Defaults to true in Node, false in /browser. */
  allowGuestFallback?: boolean;
  /** Retry POSTs on transient network/server failures. Defaults to true in Node, false in /browser. */
  retryMutations?: boolean;
  /** Called once after a 402 response; request is retried after this resolves. */
  onPaymentRequired?: () => Promise<void>;
}

/** Current user profile returned by GET /user. */
export interface UserSelf {
  id: string;
}

export interface CreateTaskParams<T extends DeckTaskType = DeckTaskType> {
  /** Stops client-side upload/submission; does not cancel an already-created cloud task. */
  signal?: AbortSignal;
  /** Space/workspace id. Falls back to createDeck({ spaceId }) or user.self id. */
  spaceId?: string;
  /** Ordered input file ids. Required for most tasks except generation/html.buildPlayer. */
  fileIds?: string[];
  /**
   * Local files for the task. When total size is under {@link INLINE_TASK_FILES_MAX_BYTES}
   * and no `fileIds` are also provided, they are sent inline on task creation as `files`.
   * Otherwise they are uploaded first and the resulting ids are appended after `fileIds`.
   */
  files?: TaskUploadInput[];
  /** Task type. */
  type: T;
  /** Optional task display name. */
  name?: string;
  /** Task parameters determined by type. */
  params?: DeckTaskTypeParams[T];
  /** Default upload options applied to files. Per-file options override these values. */
  upload?: TaskUploadOptions;
}

export interface TaskShortcutParams<T extends DeckTaskType> extends Omit<CreateTaskParams<T>, 'type'> {}

export interface ListTasksParams<T extends DeckTaskType = DeckTaskType> {
  signal?: AbortSignal;
  /** Space/workspace id. Falls back to createDeck({ spaceId }) or user.self id. */
  spaceId?: string;
  /** Optional task type filter. */
  type?: T;
  /** Start index for pagination. */
  startIndex?: number;
  /** Max results for pagination. */
  maxResults?: number;
}

export interface WaitForTaskOptions {
  /** Space containing this task. Defaults to the client's space. */
  spaceId?: string;
  /** Stops waiting; does not cancel the cloud task. */
  signal?: AbortSignal;
  /** Timeout in seconds. Defaults to 300. */
  timeout?: number;
  /** Use Server-Sent Events first, then fall back to polling. Defaults to true. */
  useEventStream?: boolean;
  /** Called whenever a task update is received. */
  onProgress?: (task: DeckTask) => void;
  /** Poll interval in milliseconds when polling is used. */
  pollInterval?: number;
}

export type TaskDownloadType = 'html' | 'pptx' | 'image';

export interface TaskDownloadOptions {
  spaceId?: string;
  signal?: AbortSignal;
  /** Download target type. Only used by generation and revamp tasks. Defaults to backend value html. */
  type?: TaskDownloadType;
}

export interface TaskDownloadUrlResult {
  /** Signed/download URL generated by the backend. */
  downloadUrl: string;
}

export type TaskDownResult<T extends DeckTaskType = DeckTaskType> = T extends
  | 'generation'
  | 'revamp'
  | 'translation'
  ? TaskDownloadUrlResult
  : DeckTaskTypeResult[T];

export interface SubscribeTaskHandlers<T extends DeckTaskType = DeckTaskType> {
  spaceId?: string;
  signal?: AbortSignal;
  /** Called for each task update. */
  onUpdate: (task: DeckTask<T>) => void;
  /** Called when the stream or parser fails. */
  onError?: (error: Error) => void;
}

export type UploadPlatform = 'oss' | 'local';

export interface AuthInfo {
  /** Upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: string;
}

export interface PartAuth {
  /** Part upload URL. */
  url: string;
  /** Headers required by the storage provider. */
  headers: Record<string, string>;
  /** Optional Authorization header returned by the backend. */
  Authorization?: string;
}

export interface UploadAuthResponse {
  /** File id to use in task fileIds. */
  id: string;
  /** Storage key. */
  key: string;
  /** File hash. */
  hash: string;
  /** Storage provider. */
  platform: UploadPlatform;
  /** Whether multipart upload is required. */
  multipart: boolean;
  /** Single upload or multipart completion auth. */
  auth?: AuthInfo;
  /** Multipart upload id. */
  multipartUploadId?: string;
  /** Multipart part size in bytes. */
  multipartPartSize?: number;
  /** Multipart part upload auth list. */
  multipartPartAuths?: PartAuth[];
}

export interface PartResult {
  /** 1-based part number. */
  partNumber: number;
  /** ETag returned by OSS-style storage. */
  eTag?: string;
  /** Hash returned by local storage. */
  hash?: string;
}

export interface RequestUploadParams {
  signal?: AbortSignal;
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** File name. */
  name: string;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
  /** Desired chunk size in bytes. */
  chunkSize?: number;
}

export type UploadInput = string | Uint8Array | ArrayBuffer | Blob;

export interface UploadOptions {
  signal?: AbortSignal;
  /** Space/workspace id. Falls back to createDeck({ spaceId }). */
  spaceId?: string;
  /** File name. Required for binary inputs that do not carry a name. */
  name?: string;
  /** File MD5 hash. Calculated automatically when omitted. */
  hash?: string;
  /** Desired chunk size in bytes. */
  chunkSize?: number;
  /** Upload progress from 0 to 1. */
  onProgress?: (percentage: number) => void;
}

export type TaskUploadOptions = Omit<UploadOptions, 'spaceId'>;

export type TaskUploadInput =
  | UploadInput
  | ({
      /** File-like value, Node.js path, or binary data to upload. Paths are Node.js-only. */
      input: UploadInput;
    } & TaskUploadOptions);

/** Normalized local file ready for inline task creation or async upload. */
export interface PreparedUpload {
  name: string;
  bytes: number;
  hash: string;
  data: Uint8Array | Blob;
  chunkSize: number;
}

export interface FileUploadResult {
  /** File id to use in task fileIds. */
  id: string;
  /** File name. */
  name: string;
  /** Storage key. */
  key?: string;
  /** File byte size. */
  bytes: number;
  /** File MD5 hash. */
  hash: string;
}

export interface FileCompressParams {
  /** Optional task id passed through to the compressor logs. */
  id?: string;
}

export type OcrLanguage =
  | 'ar'
  | 'bg'
  | 'cs'
  | 'da'
  | 'de'
  | 'el'
  | 'en'
  | 'es'
  | 'et'
  | 'fi'
  | 'fr'
  | 'hu'
  | 'id'
  | 'it'
  | 'ja'
  | 'ko'
  | 'lt'
  | 'lv'
  | 'nb'
  | 'nl'
  | 'pl'
  | 'pt'
  | 'ro'
  | 'ru'
  | 'sk'
  | 'sl'
  | 'sv'
  | 'tr'
  | 'uk'
  | 'zh-hans'
  | 'zh-hant'
  | 'ara'
  | 'bul'
  | 'ces'
  | 'dan'
  | 'deu'
  | 'grek'
  | 'eng'
  | 'spa'
  | 'est'
  | 'fin'
  | 'fra'
  | 'hun'
  | 'ind'
  | 'ita'
  | 'jpn'
  | 'kor'
  | 'lit'
  | 'lav'
  | 'nor'
  | 'nld'
  | 'pol'
  | 'por'
  | 'ron'
  | 'rus'
  | 'slk'
  | 'slv'
  | 'swe'
  | 'tur'
  | 'ukr'
  | 'chi_sim'
  | 'chi_tra';

export interface ImageOcrParams {
  /** OCR language code. */
  language: OcrLanguage;
}

export interface PptxSplitParams {
  /** Slide indexes to keep, 1-based. If omitted, every slide is split. */
  indexes?: number[];
  /** Allowed slide size as [width, height]. */
  allowSize?: [width: number, height: number];
  /** Expected PPT id to write. */
  pptId?: string;
  /** Expected version ids to write. Must match slide count or selected indexes. */
  versionIds?: string[];
  /** Replacement file pairs as [relativePath, keyPath]. */
  replaceFiles?: [relativePath: string, keyPath: string][];
}

export interface PptxContactId {
  /** PPT id. */
  pptId: string;
  /** Branch id. */
  branchId: string;
}

export interface PptxSectionItem {
  /** Section name. */
  name: string;
  /** Number of slides in this section. */
  count: number;
}

export interface PptxJoinParams {
  /** 1-based slide indexes to hide. */
  hiddens?: number[];
  /** Contact id to preserve or write. */
  contactId?: PptxContactId;
  /** Section metadata. */
  sections?: PptxSectionItem[];
  /** Changed layout map. */
  changedLayoutMap?: [sourceSlideIndex: number, targetSlideIndex: number][];
  /** Whether to auto resize slides. */
  autoResize?: boolean;
}

export type PptxGetFontInfoParams = Record<never, never>;

export interface PptxGetTextShapesParams {
  /** Whether returned shapes include child shapes. */
  hasChildren?: boolean;
  /** Page numbers to inspect. */
  pickPages?: number[];
  /** Image filter by area ratio from 0 to 1. */
  imageFilter?: number;
  /** Whether duplicate shape ids should be fixed. */
  needFixDuplicatedShapeId?: boolean;
  /** Include layout shapes. */
  includeLayout?: boolean;
  /** Include master shapes. */
  includeMaster?: boolean;
  /** Include speaker notes. */
  includeNotes?: boolean;
  /** Ignore empty text shapes. */
  ignoreEmptyText?: boolean;
  /** Return only brief shape information. */
  onlyBrief?: boolean;
}

export interface PptxEmbedFontsParams {
  /** Font family names to embed into the PPTX. */
  usedFonts: string[];
}

export interface ConvertPptToImageParams {
  /** Output image width/resolution. */
  resolution?: 1080 | 1920 | 2560;
  /** Output image format. */
  format?: 'png' | 'jpg';
}

export type ConvertPptToPptxParams = Record<never, never>;
export type ConvertPptToPdfParams = Record<never, never>;
export type ConvertDocToPdfParams = Record<never, never>;
export type ConvertPptToVideoParams = Record<never, never>;

export interface ConvertPdfToImageParams {
  /** Long-edge max resolution. Defaults to backend value 1080. */
  resolution?: number;
  /** Output image format. */
  format?: 'png' | 'jpg';
}

export type ConvertKeynoteToImageParams = Record<never, never>;
export type ConvertKeynoteToPdfParams = Record<never, never>;

export interface ConvertKeynoteToHtmlParams {
  /** Whether the backend should create a hosted HTML path. The task API currently overrides this to false. */
  isHost?: boolean;
}

export interface ConvertHtmlToPngParams {
  /** Render scale. */
  scale?: number;
  /** Capture the full page. */
  fullPage?: boolean;
  /** Inline HTML content. Ignored when fileIds are used. */
  html?: string;
  /** Viewport width. */
  width?: number;
  /** Viewport height. */
  height?: number;
}

export interface ConvertMarkdownToPngParams {
  /** Render scale. */
  scale?: number;
  /** Theme name. */
  theme?: 'light' | 'dark';
  /** Page width. */
  pageWidth?: number;
  /** Inline markdown content. Ignored when fileIds are used. */
  markdown?: string;
}

export interface ConvertHtmlToPptxParams {
  /** Whether to embed fonts in the output PPTX. */
  needEmbedFonts?: boolean;
  /** Inline HTML content. Ignored when fileIds are used. */
  html?: string;
  /** Slide width. */
  width?: number;
  /** Slide height. */
  height?: number;
}

export type VideoCompressParams = Record<never, never>;
export type ImageConvertWebpParams = Record<never, never>;

export interface HtmlBuildPlayerContent {
  /** OSS/storage key for this content page. */
  key?: string;
  /** Inline HTML for this content page. */
  html?: string;
}

export interface HtmlBuildPlayerParams {
  /** HTML pages/segments. Each item should provide either key or html. */
  contents: HtmlBuildPlayerContent[];
  /** Player page width. */
  pageWidth: number;
  /** Player page height. */
  pageHeight: number;
  /** Player title. */
  title: string;
  /** Player description. */
  description: string;
  /** Brand mark position. */
  brandMarkPosition: 'none' | 'leftTop' | 'leftBottom' | 'rightTop' | 'rightBottom';
}

export interface ImageResizeParams {
  /** Maximum width. Either maxWidth or maxHeight is required by the backend. */
  maxWidth?: number;
  /** Maximum height. Either maxWidth or maxHeight is required by the backend. */
  maxHeight?: number;
  /** Optional target storage path. */
  target?: string;
}

export interface GenerationParams {
  /** User input text. */
  inputText?: string;
  /** Whether to enable search. */
  enableSearch?: boolean;
  /** Whether to use an advanced model. */
  advancedModel?: boolean;
  /** Whether to enable fast mode. */
  fastMode?: boolean;
  /** Content generation intent. */
  intent?: string;
  /** Target audience. */
  audience?: string;
  /** Expected page count. */
  pageCount?: number;
  /** Document author. */
  author?: string;
}

export interface TranslationParams {
  /** Translation model. */
  model: 'Standard' | 'Pro';
  /** Source language. */
  from: string;
  /** Target language. */
  to: string;
  /** Whether to use glossary. */
  useGlossary: boolean;
  /** Whether to translate images inside the document. */
  imageTranslate: boolean;
}

export interface RevampParams {
  /** Output language. */
  lang?: string;
}

export interface PptxSlideResult {
  /** File MD5 hash. */
  hash: string;
  /** Storage path or URL. */
  path: string;
  /** File size in bytes. */
  bytes: number;
  /** Whether the slide was hidden. */
  hidden?: boolean;
  /** Snapshot image path when available. */
  snapImage?: string;
  /** Speaker notes text. */
  notes?: string;
  /** Version id written to the split slide. */
  versionId?: string;
}

export interface PptxSplitResult {
  /** Source PPT metadata. */
  ppt: {
    /** Source slide size as [width, height]. */
    size: [width: number, height: number];
  };
  /** Section metadata read from source file. */
  sections: PptxSectionItem[];
  /** Split slide files. */
  slides: PptxSlideResult[];
}

export interface PptxFontInfo {
  /** Font names used by the document. */
  fonts: string[];
  /** Whether the document contains embedded fonts. */
  embeddedFont: boolean;
  /** Whether embedded fonts are subsets. */
  subsetFont: boolean;
}

export interface PptxShapeFile {
  /** Storage path or URL. */
  path?: string;
  /** File extension including dot. */
  ext?: string;
  /** Description, commonly the original file name. */
  desc?: string;
  /** File size in bytes. */
  bytes?: number;
  /** MD5 hash. */
  hash?: string;
}

export interface PptxTextRun {
  /** Text content. */
  text: string;
  /** Font family. */
  font?: string;
  /** Font size. */
  fontSize?: number;
  /** Text color. */
  textColor?: string;
  /** Text opacity/alpha. */
  textAlpha?: number;
  /** Bold marker from PPT XML. */
  fontBold?: string;
  /** Italic marker from PPT XML. */
  fontItalic?: string;
  /** Underline marker from PPT XML. */
  fontUnderline?: string;
  /** Strike marker from PPT XML. */
  fontStrike?: string;
  /** Character spacing. */
  charSpacing?: number;
}

export interface PptxTextParagraph {
  /** Horizontal alignment. */
  horizontalAlignment?: string;
  /** Whether text reads right-to-left. */
  rtl?: '0' | '1';
  /** Text runs in this paragraph. */
  children: PptxTextRun[];
}

export interface PptxShapeContent {
  /** Plain text content. */
  text?: string;
  /** Rich text paragraphs. */
  textNode?: PptxTextParagraph[];
  /** Picture file info. */
  picture?: PptxShapeFile & {
    crop?: {
      left?: number;
      top?: number;
      right?: number;
      bottom?: number;
      width?: number;
      height?: number;
      offX?: number;
      offY?: number;
    };
    alpha?: number;
  };
  /** Chart info. */
  chart?: { rId?: string; type: 'bar' | 'line' | 'pie' };
  /** Video file info. */
  video?: PptxShapeFile & { thumbnail?: PptxShapeFile };
  /** Audio file info. */
  audio?: PptxShapeFile & { thumbnail?: PptxShapeFile };
}

export interface PptxShape {
  /** Shape id. */
  id: number;
  /** Shape name. */
  name: string;
  /** Shape category. */
  type: 'shape' | 'picture' | 'group' | 'connectionShape' | 'graphicFrame';
  /** Placeholder type. */
  phType?: string;
  /** Whether the shape is a text box. */
  txBox?: boolean;
  /** Whether the shape is hidden. */
  hidden?: boolean;
  /** Preset geometry name. */
  shape?: string;
  /** Shape path in the slide tree. */
  path?: string;
  /** Width. */
  width: number;
  /** Height. */
  height: number;
  /** Left offset. */
  left: number;
  /** Top offset. */
  top: number;
  /** Rotation. */
  rotation?: number;
  /** Vertical flip. */
  flipV?: boolean;
  /** Horizontal flip. */
  flipH?: boolean;
  /** Font family. */
  font?: string;
  /** Font size. */
  fontSize?: number;
  /** Text color. */
  textColor?: string;
  /** Fill color. */
  color?: string;
  /** Children for group shapes. */
  children?: PptxShape[];
  /** Shape content. */
  content?: PptxShapeContent;
}

export interface PptxPageInfo {
  /** Page type. */
  type: 'slide' | 'master' | 'layout';
  /** Page file path. */
  file: string;
  /** Layout file path for slide pages. */
  layoutFile?: string;
  /** Master file path for slide/layout pages. */
  masterFile?: string;
  /** Shape tree. */
  spTree: PptxShape[];
  /** Speaker notes. */
  notes?: string[];
  /** Embedded text entries. */
  embedText?: { text: string; fontInfo?: PptxFontInfo }[];
  /** Color mapping. */
  colorMap?: Record<string, string>;
}

export interface PptxGetTextShapesResult {
  /** Number of pages. */
  pageNum: number;
  /** Slide width. */
  width: number;
  /** Slide height. */
  height: number;
  /** Slide page info. */
  slides: PptxPageInfo[];
  /** Layout page info when requested. */
  layouts?: PptxPageInfo[];
  /** Master page info when requested. */
  masters?: PptxPageInfo[];
  /** Picked PPTX path when duplicate shape ids were fixed. */
  pickedPptx?: string;
  /** Extracted image map keyed by original relative path. */
  images?: Record<string, FileResult>;
  /** Whether duplicate shape ids were detected. */
  hasDuplicatedShapeId?: boolean;
}

export interface ImageOcrResult {
  /** Tesseract job id. */
  jobId?: string;
  /** OCR data payload. */
  data: {
    /** Recognized text. */
    text: string;
    /** Mean confidence. */
    confidence?: number;
    /** Recognized blocks. */
    blocks?: MetadataValue[];
    /** Recognized paragraphs. */
    paragraphs?: MetadataValue[];
    /** Recognized lines. */
    lines?: MetadataValue[];
    /** Recognized words. */
    words?: MetadataValue[];
    /** Recognized symbols. */
    symbols?: MetadataValue[];
    [key: string]: MetadataValue | undefined;
  };
}

export interface HtmlToPptxResult {
  /** Output PPTX file. */
  target: FileResult;
  /** Fonts used while converting HTML to PPTX. */
  usedFonts: string[];
}

/**
 * 解析类任务的参数与结果定义在 `./parse/types.ts`，此处只做转出，
 * 免得同一份服务端契约在两个文件里各写一遍、各自漂移。
 */
export type {
  ConvertTaskParams,
  ConvertTaskResult,
  DocxParseTaskParams,
  HtmlGetByUrlTaskParams,
  KeynoteParseTaskParams,
  PdfParseTaskParams,
  PptxParseTaskParams,
};

/** `pptx.parse` 的结果：PPTX 对象模型 */
export type PptxTaskParseResult = PptxParseResult;

export interface DeckTaskTypeParams {
  'file.compress': FileCompressParams;
  'image.ocr': ImageOcrParams;
  'pptx.split': PptxSplitParams;
  'pptx.join': PptxJoinParams;
  'pptx.getFontInfo': PptxGetFontInfoParams;
  'pptx.getTextShapes': PptxGetTextShapesParams;
  'pptx.embedFonts': PptxEmbedFontsParams;
  'convertor.ppt2image': ConvertPptToImageParams;
  'convertor.ppt2pptx': ConvertPptToPptxParams;
  'convertor.ppt2pdf': ConvertPptToPdfParams;
  'convertor.doc2pdf': ConvertDocToPdfParams;
  'convertor.ppt2video': ConvertPptToVideoParams;
  'convertor.pdf2image': ConvertPdfToImageParams;
  'convertor.keynote2image': ConvertKeynoteToImageParams;
  'convertor.keynote2html': ConvertKeynoteToHtmlParams;
  'convertor.keynote2pdf': ConvertKeynoteToPdfParams;
  'convertor.html2png': ConvertHtmlToPngParams;
  'convertor.markdown2png': ConvertMarkdownToPngParams;
  'convertor.html2pptx': ConvertHtmlToPptxParams;
  'html.buildPlayer': HtmlBuildPlayerParams;
  'video.compress': VideoCompressParams;
  'image.convertWebp': ImageConvertWebpParams;
  'image.resize': ImageResizeParams;
  'pdf.pdfParse': PdfParseTaskParams;
  'pptx.parse': PptxParseTaskParams;
  'docx.parseTextAndImage': DocxParseTaskParams;
  'keynote.parseTextAndImage': KeynoteParseTaskParams;
  'html.getByURL': HtmlGetByUrlTaskParams;
  'parse.convert': ConvertTaskParams;
  generation: GenerationParams;
  translation: TranslationParams;
  revamp: RevampParams;
}

export interface DeckTaskTypeResult {
  'file.compress': ConvertFileResult;
  'image.ocr': ImageOcrResult;
  'pptx.split': PptxSplitResult;
  'pptx.join': FileResult;
  'pptx.getFontInfo': PptxFontInfo;
  'pptx.getTextShapes': PptxGetTextShapesResult;
  'pptx.embedFonts': FileResult;
  'convertor.ppt2image': ConvertFileResult[];
  'convertor.ppt2pptx': ConvertFileResult[];
  'convertor.ppt2pdf': ConvertFileResult[];
  'convertor.doc2pdf': ConvertFileResult[];
  'convertor.ppt2video': ConvertFileResult[];
  'convertor.pdf2image': ConvertFileResult[];
  'convertor.keynote2image': ConvertFileResult[];
  'convertor.keynote2html': ConvertFileResult[];
  'convertor.keynote2pdf': ConvertFileResult[];
  'convertor.html2png': FileResult;
  'convertor.markdown2png': FileResult;
  'convertor.html2pptx': HtmlToPptxResult;
  'html.buildPlayer': FileResult;
  'video.compress': FileResult;
  'image.convertWebp': FileResult;
  'image.resize': FileResult;
  'pdf.pdfParse': PdfParseResult;
  'pptx.parse': PptxParseResult;
  'docx.parseTextAndImage': DocxParseResult;
  'keynote.parseTextAndImage': KeynoteParseResult;
  'html.getByURL': HtmlGetByUrlResult;
  'parse.convert': ConvertTaskResult;
  generation: Required<{ image?: FileResult; pptx?: FileResult; html?: FileResult }>;
  translation: FileResult;
  revamp: Required<{ image?: FileResult; pptx?: FileResult; html?: FileResult }>;
}

export interface DeckTaskTypePreview {
  'file.compress': { bytes: number };
  'pptx.split': { fileNumber: number };
  'pptx.join': { bytes: number };
  'convertor.html2pptx': FileResult[];
  'video.compress': { bytes: number };
  'image.resize': { bytes: number };
  generation: { previewURL?: string };
  translation: { previewURL?: string; before: FileResult[]; after: FileResult[] };
  revamp: { previewURL?: string; before: FileResult[] };
  'image.ocr': never;
  'pptx.getFontInfo': never;
  'pptx.getTextShapes': never;
  'pptx.embedFonts': never;
  'convertor.ppt2image': never;
  'convertor.ppt2pptx': never;
  'convertor.ppt2pdf': never;
  'convertor.doc2pdf': never;
  'convertor.ppt2video': never;
  'convertor.pdf2image': never;
  'convertor.keynote2image': never;
  'convertor.keynote2html': never;
  'convertor.keynote2pdf': never;
  'convertor.html2png': never;
  'convertor.markdown2png': never;
  'html.buildPlayer': never;
  'image.convertWebp': never;
  'pdf.pdfParse': never;
  'parse.convert': never;
  'pptx.parse': never;
  'docx.parseTextAndImage': never;
  'keynote.parseTextAndImage': never;
  'html.getByURL': never;
}
